import {
  SismoConnectButton,
  AuthType,
  SismoConnectResponse,
  ClaimType,
} from "@sismo-core/sismo-connect-react";
import { ConnectButton } from "@rainbow-me/rainbowkit";
import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useForm } from "react-hook-form";

const Home: NextPage = () => {
  const {
    register,
    handleSubmit,
    formState: { errors },
  } = useForm();
  return (
    <div className={styles.container}>
      <Head>
        <title>RainbowKit App</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <main className={styles.main}>
        <ConnectButton />

        <form onSubmit={handleSubmit((data) => console.log(data))}>
          <div>
            <label
              htmlFor="appid"
              className="block text-sm font-medium leading-6 text-gray-900"
            >
              Sismo AppID
            </label>
            <div className="mt-2">
              <input
                {...register("appid")}
                name="appid"
                id="appid"
                className="block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6"
                placeholder="sismo-app-id"
              />
            </div>
          </div>
          <div>
            <label
              htmlFor="groupID"
              className="block text-sm font-medium leading-6 text-gray-900"
            >
              Simso groupID
            </label>
            <div className="mt-2">
              <input
                {...register("groupid")}
                name="groupID"
                id="groupID"
                className="block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6"
                placeholder="sismo-group-id"
              />
            </div>
          </div>
          <div>
            <label
              htmlFor="entryPoint"
              className="block text-sm font-medium leading-6 text-gray-900"
            >
              Paymaster entryPoint
            </label>
            <div className="mt-2">
              <input
                {...register("entrypoint")}
                name="entrypoint"
                id="entryPoint"
                className="block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6"
                placeholder="0x5FF137D4b0FDCD49DcA30c7CF57E578a026d2789"
              />
            </div>
          </div>

          <input type="submit" />
        </form>
      </main>

      <footer className={styles.footer}>
        <a href="https://rainbow.me" rel="noopener noreferrer" target="_blank">
          Made with ❤️ by your frens
        </a>
      </footer>
    </div>
  );
};

export default Home;
